# Generated by Django 4.1 on 2023-10-11 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_rename_members_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='age',
            new_name='telefoonnummer',
        ),
    ]
