# Generated by Django 4.1 on 2023-10-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_rename_age_member_telefoonnummer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='telefoonnummer',
            field=models.CharField(max_length=100),
        ),
    ]
