# Generated by Django 4.1 on 2023-10-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0008_bieding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('straat', models.CharField(max_length=50)),
                ('postcode', models.CharField(max_length=50)),
                ('plaats', models.CharField(max_length=50)),
                ('gewijzigd', models.DateTimeField()),
            ],
        ),
    ]
