# Generated by Django 4.1 on 2023-10-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0013_role_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gebruiker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('passwd', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
