# Generated by Django 4.1 on 2023-10-27 11:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0016_alter_gebruiker_username_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='gebruiker',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='gebruiker',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gebruiker',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gebruiker',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='gebruiker',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
