# Generated by Django 4.1 on 2023-11-15 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0022_alter_gebruiker_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gebruiker',
            name='role',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='playground.role'),
        ),
    ]
