# Generated by Django 4.1 on 2024-01-10 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0023_alter_gebruiker_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='bieding',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='playground.status'),
        ),
    ]
