# Generated by Django 4.1 on 2024-01-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0024_bieding_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='datum',
            field=models.DateField(null=True),
        ),
    ]
