# Generated by Django 4.1 on 2023-10-11 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0005_alter_member_telefoonnummer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='fname',
            new_name='username',
        ),
    ]
