# Generated by Django 4.1 on 2023-10-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0009_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=50)),
                ('waarde', models.IntegerField()),
                ('landingspagina', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statuscode', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
