# Generated by Django 4.1 on 2023-10-27 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0014_gebruiker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gebruiker',
            name='passwd',
        ),
    ]
