# Generated by Django 4.1 on 2023-10-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0019_remove_role_user_gebruiker_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='gebruiker',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
