# Generated by Django 4.1 on 2024-01-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0025_alter_home_datum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bieding',
            name='bod',
            field=models.IntegerField(null=True),
        ),
    ]
