# Generated by Django 4.1 on 2024-01-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0026_alter_bieding_bod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bieding',
            name='statusdatum',
            field=models.DateField(null=True),
        ),
    ]
